### ISSUE TITLE
Wrong UnicodeString to unicode conversion for surrogate pair type characters

### ISSUE THREAD

**Issue by ohadshany** [ovalhub/pyicu#30]
If a UnicodeString object contains characters that are UTF16 surrogate pair (i.e u' \U000216d5') then direct conversion to unicode results in an invalid value. For example:

`import icu`
`print unicode(icu.UnicodeString(u'\U000216d5'))`
Results in:  u'\ud845\uded5'

Which is wrong since the correct value should be u' \U000216d5'

You can also see that `UnicodeString(unicode(icu.UnicodeString(u' \U000216d5')))` fails because of incorrect value.

A quick fix is to use explicit encoding like this:
`unicode(icu.UnicodeString(u'\U000216d5').encode('utf8'), 'utf8')`

I've encountered this problem on linux python 2.7 with PyICU 1.9.3 and ICU 57 and also with PyICU 1.8 and ICU 53.

**Comment by ovalhub** [comment]
On Tue, 30 Aug 2016, ohadshany wrote:

> If a UnicodeString object contains characters that are UTF16 surrogate pair (i.e u' \U000216d5') then direct conversion to unicode results in an invalid value. For example:
>
> `import icu`
> `print unicode(icu.UnicodeString(u'\U000216d5'))`
> Results in:  u'\ud845\uded5'

For me, it results in:

   >>> unicode(UnicodeString(u'\U000216d5'))
   u'\U000216d5'

   >>> print unicode(UnicodeString(u'\U000216d5'))
   that fails because "...'latin-1' codec can't encode characters..."

   >>> repr(unicode(UnicodeString(u'\U000216d5')))
   "u'\\U000216d5'"

   >>> UnicodeString(u'\U000216d5').length()
   2
   >>> UnicodeString(u'\U000216d5').countChar32()
   1

I think that a bug is still possible because of the possibly iffy 
optimization in PyObject_AsUnicodeString, line 297 in common.cpp. There, if 
Python's Py_Unicode type size is the same as that of UChar (16 bits), the 
UChar characters are just copied into the UnicodeString. In the other case, 
where Python's Py_UNICODE is 32 bits (which is the case on Linux, iirc), 
then the u_strFromUTF32() function is used to convert from UTF32.

Since I can't easily reproduce this right now, could you try taking the 
first case out and always go through the u_strFromUTF32() call and see if 
that fixes the problem ?

I could also be wrong about this...

Thanks !

Andi..

**Comment by ovalhub** [comment]
This was reworked in PyICU 1.9.5 for both Python 2 and Python 3.
