### ISSUE TITLE
Unable to install pyicu with pip in python3

### ISSUE THREAD

**Issue by elcolie** [ovalhub/pyicu#99]
OS: `OSX 10.14.2`
Python Version `3.7.3`

```bash
$ pip install PyICU
Collecting PyICU
  Using cached https://files.pythonhosted.org/packages/87/10/fdf5842f42834f6e3141668b607c07bc3c94de39acf582c3d4015e7a7fc5/PyICU-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Package icu-i18n was not found in the pkg-config search path.
    Perhaps you should add the directory containing `icu-i18n.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'icu-i18n' found
    (running 'icu-config --version')
    (running 'pkg-config --modversion icu-i18n')
    Traceback (most recent call last):
      File "/private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/setup.py", line 62, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/setup.py", line 65, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "/private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/setup.py", line 18, in check_output
        return subprocess_check_output(popenargs)
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/setup.py", line 68, in <module>
        ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
      File "/private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/setup.py", line 18, in check_output
        return subprocess_check_output(popenargs)
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/Users/sarit/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'icu-i18n')' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/setup.py", line 73, in <module>
        ''')
    RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/pip-install-tmtes8h2/PyICU/
```

**Comment by ovalhub** [comment]
You need to configure the variables in setup.py manually since you don't have icu-config installed.

Andi..

**Comment by drupchen** [comment]
Same bug. I don't want to mess around with the package. I just want to install it the way it is meant to be installed. Could you fix that issue instead of proposing to hack your own package ?

Thanking you in advance

**Comment by ovalhub** [comment]
> On Apr 15, 2019, at 04:41, drupchen <notifications@github.com> wrote:
> 
> Same bug. I don't want to mess around with the package. I just want to install it the way it is meant to be installed. Could you fix that issue instead of proposing to hack your own package ?
> 
There is no issue. If you want to install PyICU, you need to install ICU first. If you've got installed in a way the PyICU build can't find it, you've got to tell it where ICU is yourself.

Andi..

**Comment by giulbia** [comment]
> Same bug. I don't want to mess around with the package. I just want to install it the way it is meant to be installed. Could you fix that issue instead of proposing to hack your own package ?
> 
> Thanking you in advance
> 
> [edit:] I managed to install by installing the `pyicu-binary` package, instead of installing the regular package.

This solution worked for me too on CentOS. Thx @drupchen

**Comment by ovalhub** [comment]
> On Jan 22, 2020, at 07:00, Giulia <notifications@github.com> wrote:
> 
> ﻿
> Same bug. I don't want to mess around with the package. I just want to install it the way it is meant to be installed. Could you fix that issue instead of proposing to hack your own package ?
> 
> Thanking you in advance
> 
If you have installed icu itself with icu-config or if pkg-config knows about the icu install then no further edits (or env var settings) are needed to tell pyicu where to find icu.

**Comment by filipegl** [comment]
try:
`sudo apt install libicu-dev`
`pip install pyicu`

**Comment by zachary-dh** [comment]
This needs to be packaged up in a regular installation pip install pyicu.   Users should not need to configure extra. Right not I can't deploy this as a requirement to a cloud function.

**Comment by ovalhub** [comment]
On Thu, 27 Aug 2020, zachary-dh wrote:

> This needs to be packaged up in a regular installation pip install pyicu. 
> Users should not need to configure extra. Right not I can't deploy this as 
> a requirement to a cloud function.

No. As that would involve shipping binaries which is something I'm not 
willing to do. There are just too many possible combinations of Python 
versions x ICU versions x OS versions + C++ compiler versions to build.
I'm also not willing to take the responsibility of shipping binaries.
Please, look for the binary fork of PyICU that suits your requirements or 
create your own cloud-installable version.

**Comment by zachary-dh** [comment]
Gotcha. Ok. I'll look into it. I also noticed python has a library called
Babel that has some similarities.

**Comment by tommyjcarpenter** [comment]
This issue is further complicated in cloud envs, when we don't have control over the system level install. In our case, this is a _transitive_ dependency of csvkit, which installs agate, which installs this package: https://github.com/wireservice/agate/issues/754

We cant do an apt-get level install as we have no control over the box outside of python requirements (AWS MWAA)

We also cant use the binary package as this is a transitive dependency

other than forking csv kit, and agate, to install the binary package of this, I'm not sure what to do,

**Comment by ovalhub** [comment]
On Sun, 14 Mar 2021, Tommy Carpenter wrote:

> This issue is further complicated in cloud envs, when we don't have 
> control over the system level install. In our case, this is a _transitive_ 
> dependency of csvkit, which installs agate, which installs this package: 
> https://github.com/wireservice/agate/issues/754
>
> We cant do an apt-get level install as we have no control over the box 
> outside of python requirements (AWS MWAA)
>
> We also cant use the binary package as this is a transitive dependency
>
> other than forking csv kit, and agate, to install the binary package of 
> this, I'm not sure what to do,

That, or talking to the package owners, in reverse transitive order, that 
include PyICU. If the cloud environments they're running in don't have the 
required software for installing PyICU, then, they in turn, can't depend on 
it either. In order to install PyICU, you need an installation of ICU that 
PyICU can be built against.

If ICU is not installed in these cloud environments, then installing PyICU 
makes no sense whatsosever as it's a wrapper library against a specific ICU 
version, the one installed on your system or the one you chose to install. 
There is no existence of PyICU without a companion install of ICU.

I'd suggest that a simpler solution to all this might be to install ICU and 
PyICU as part of the base cloud environment these packages they run under.
Some Linux distributions, some BSD distributions already include ICU 
and PyICU.

If AWS MWAA doesn't let you install ICU and PyICU, then maybe it's not 
meeting your requirements and alternatives should be considered.

**Comment by tommyjcarpenter** [comment]
Look at this from the top level user perspective;
- I only can control pip requirements of MY top level application
- I do not even know what ICU is, or agate is; I don't use them (directly), this is a transitive type of dependency hell
- the phrasing "if they cloud envs they are running in" is odd in the sense that, these packages don't "know" they are being used in the cloud; we are running *our* top level application in the cloud

If the end result here is, that we need to abandon a CSV library (csvkit is our top level import) because of a transitive dep, then so be it, but from the top level perspective where they are not directly using or caring about ICU, I think you can see how that could be frusterating (not suggesting a fix here).

**Comment by ovalhub** [comment]
On Mon, 15 Mar 2021, Tommy Carpenter wrote:

> Look at this from the top level user perspective;
> - I only can control pip requirements of MY top level application
> - I do not even know what ICU is, or agate is; I don't use them (directly), this is a transitive type of dependency hell
> - the phrasing "if they cloud envs they are running in" is odd in the sense that, these packages don't "know" they are being used in the cloud; we are running *our* top level application in the cloud

Yes, this is like DLL hell but "in the cloud".
In both cases, as the top level user, you are in charge of the entire stack 
of software your application requires, transively.

> If the end result here is, that we need to abandon a CSV library (csvkit 
> is our top level import) because of a transitive dep, then so be it, but 
> from the top level perspective where they are not directly using or caring 
> about ICU, I think you can see how that could be frusterating (not 
> suggesting a fix here).

I completely understand the frustration but you are still in charge. And 
that is why you can make decisions like the one you mention above (dropping 
csvkit). Wishing the problem away is going to end in frustration.
